# The project language
os: linux
dist: bionic
language: c

jobs:
  include:
    - name: "ppc-linux static"
      compiler: powerpc-linux-gnu-gcc
      env:
        - CONFIGURE_FLAGS="--enable-static --disable-openssl --disable-gettext"
      addons:
        apt:
          packages:
            - gcc-powerpc-linux-gnu libc-dev-powerpc-cross
            - qemu qemu-user-static binfmt-support

    - name: "ppc64-linux static"
      compiler: powerpc64-linux-gnu-gcc
      env:
        - CONFIGURE_FLAGS="--enable-static --disable-openssl --disable-gettext"
      addons:
        apt:
          packages:
            - gcc-powerpc64-linux-gnu libc-dev-ppc64-cross
            - qemu qemu-user-static binfmt-support

script:
  - cd rhash
  - ./configure --sysconfdir=/etc $CONFIGURE_FLAGS
  - make
  - test -f ./rhash || cat config.mak librhash/config.mak config.log
  - make print-info test-lib
  - make test
